[root@rdsdbsrvr82 /]# cd dev/
[root@rdsdbsrvr82 dev]# ls
agpgart          hidraw0             pts       tty16  tty42  ttyS2
autofs           hpet                random    tty17  tty43  ttyS3
block            hugepages           raw       tty18  tty44  uhid
bsg              hwrng               rtc       tty19  tty45  uinput
btrfs-control    initctl             rtc0      tty2   tty46  urandom
bus              input               sda       tty20  tty47  usbmon0
cdrom            kmsg                sda1      tty21  tty48  usbmon1
char             log                 sda2      tty22  tty49  usbmon2
console          loop-control        sdb       tty23  tty5   vcs
core             lp0                 sdb1      tty24  tty50  vcs1
cpu              lp1                 sg0       tty25  tty51  vcs2
cpu_dma_latency  lp2                 sg1       tty26  tty52  vcs3
cuse             lp3                 sg2       tty27  tty53  vcs4
disk             mapper              shm       tty28  tty54  vcs5
dm-0             mcelog              snapshot  tty29  tty55  vcs6
dm-1             mem                 snd       tty3   tty56  vcsa
dm-2             memory_bandwidth    sr0       tty30  tty57  vcsa1
dm-3             midi                stderr    tty31  tty58  vcsa2
dm-4             mqueue              stdin     tty32  tty59  vcsa3
dm-5             net                 stdout    tty33  tty6   vcsa4
dm-6             network_latency     tty       tty34  tty60  vcsa5
dm-7             network_throughput  tty0      tty35  tty61  vcsa6
dmmidi           null                tty1      tty36  tty62  vfio
dri              nvram               tty10     tty37  tty63  vga_arbiter
fb0              ol_rdsdbsrvr81      tty11     tty38  tty7   vhci
fd               oracleasm           tty12     tty39  tty8   vhost-net
fd0              port                tty13     tty4   tty9   vmci
full             ppp                 tty14     tty40  ttyS0  vsock
fuse             ptmx                tty15     tty41  ttyS1  zero
[root@rdsdbsrvr82 dev]# ls
agpgart          hidraw0             pts       tty16  tty42  ttyS2
autofs           hpet                random    tty17  tty43  ttyS3
block            hugepages           raw       tty18  tty44  uhid
bsg              hwrng               rtc       tty19  tty45  uinput
btrfs-control    initctl             rtc0      tty2   tty46  urandom
bus              input               sda       tty20  tty47  usbmon0
cdrom            kmsg                sda1      tty21  tty48  usbmon1
char             log                 sda2      tty22  tty49  usbmon2
console          loop-control        sdb       tty23  tty5   vcs
core             lp0                 sdb1      tty24  tty50  vcs1
cpu              lp1                 sg0       tty25  tty51  vcs2
cpu_dma_latency  lp2                 sg1       tty26  tty52  vcs3
cuse             lp3                 sg2       tty27  tty53  vcs4
disk             mapper              shm       tty28  tty54  vcs5
dm-0             mcelog              snapshot  tty29  tty55  vcs6
dm-1             mem                 snd       tty3   tty56  vcsa
dm-2             memory_bandwidth    sr0       tty30  tty57  vcsa1
dm-3             midi                stderr    tty31  tty58  vcsa2
dm-4             mqueue              stdin     tty32  tty59  vcsa3
dm-5             net                 stdout    tty33  tty6   vcsa4
dm-6             network_latency     tty       tty34  tty60  vcsa5
dm-7             network_throughput  tty0      tty35  tty61  vcsa6
dmmidi           null                tty1      tty36  tty62  vfio
dri              nvram               tty10     tty37  tty63  vga_arbiter
fb0              ol_rdsdbsrvr81      tty11     tty38  tty7   vhci
fd               oracleasm           tty12     tty39  tty8   vhost-net
fd0              port                tty13     tty4   tty9   vmci
full             ppp                 tty14     tty40  ttyS0  vsock
fuse             ptmx                tty15     tty41  ttyS1  zero
