[oracle@rdsdbsrvr82 2022_02_11]$ locate catalog database
/etc/default/grub-oracle-database-preinstall-19c.orabackup
/etc/rc.d/init.d/oracle-database-preinstall-19c-firstboot
/etc/security/limits.d/oracle-database-preinstall-19c.conf
/etc/sgml/docbook/xmlcatalog
/etc/sysconfig/oracle-database-preinstall-19c
/etc/sysconfig/oracle-database-preinstall-19c/oracle-database-preinstall-19c-verify
/etc/sysconfig/oracle-database-preinstall-19c/oracle-database-preinstall-19c.conf
/etc/sysconfig/oracle-database-preinstall-19c/oracle-database-preinstall-19c.param
/etc/sysctl.d/99-oracle-database-preinstall-19c-sysctl.conf
/etc/xml/catalog
/home/oracle/.cache/webkit/icondatabase
/home/oracle/.cache/webkit/icondatabase/WebpageIcons.db
/home/oracle/.config/pulse/1e1d8997bab74296b390af714242ef89-card-database.tdb
/u01/app/oracle/product/19c/OPatch/auto/database
/u01/app/oracle/product/19c/OPatch/auto/database/bin
/u01/app/oracle/product/19c/OPatch/auto/database/modules
/u01/app/oracle/product/19c/OPatch/auto/database/bin/BootStrapping.pl
/u01/app/oracle/product/19c/OPatch/auto/database/bin/CleanUp.pl
/u01/app/oracle/product/19c/OPatch/auto/database/bin/ExportPath.pl
/u01/app/oracle/product/19c/OPatch/auto/database/bin/OPatchAuto11.pl
/u01/app/oracle/product/19c/OPatch/auto/database/bin/OPatchAutoBinary.pl
/u01/app/oracle/product/19c/OPatch/auto/database/bin/OPatchAutoDB.pl
/u01/app/oracle/product/19c/OPatch/auto/database/bin/OPatchAutoHelper.pl
/u01/app/oracle/product/19c/OPatch/auto/database/bin/OPatchAutoRHP.pl
/u01/app/oracle/product/19c/OPatch/auto/database/bin/PatchLevelReport.pl
/u01/app/oracle/product/19c/OPatch/auto/database/bin/RemoteCommandExecution.pl
/u01/app/oracle/product/19c/OPatch/auto/database/bin/RemoteHostExecutor.pl
/u01/app/oracle/product/19c/OPatch/auto/database/bin/RootSessionValidation.pl
/u01/app/oracle/product/19c/OPatch/auto/database/bin/ZipUnzip.pl
/u01/app/oracle/product/19c/OPatch/auto/database/bin/chgchown.pl
/u01/app/oracle/product/19c/OPatch/auto/database/bin/detecthas.pl
/u01/app/oracle/product/19c/OPatch/auto/database/bin/module
/u01/app/oracle/product/19c/OPatch/auto/database/bin/opatchauto.properties
/u01/app/oracle/product/19c/OPatch/auto/database/bin/opatchauto11.sh
/u01/app/oracle/product/19c/OPatch/auto/database/bin/remotevalidation.sh
/u01/app/oracle/product/19c/OPatch/auto/database/bin/module/BootStrapCommandOptions.pm
/u01/app/oracle/product/19c/OPatch/auto/database/bin/module/ClassPathLib.pm
/u01/app/oracle/product/19c/OPatch/auto/database/bin/module/CommandOptions.pm
/u01/app/oracle/product/19c/OPatch/auto/database/bin/module/DBUtilServices.pm
/u01/app/oracle/product/19c/OPatch/auto/database/bin/module/DBValidationUtil.pm
/u01/app/oracle/product/19c/OPatch/auto/database/bin/module/ExportPath.pm
/u01/app/oracle/product/19c/OPatch/auto/database/bin/module/OPatchAuto11CommandOptions.pm
/u01/app/oracle/product/19c/OPatch/auto/database/bin/module/OPatchAutoBinaryCommandOptions.pm
/u01/app/oracle/product/19c/OPatch/auto/database/bin/module/OPatchAutoCommandOptions.pm
/u01/app/oracle/product/19c/OPatch/auto/database/modules/com.oracle.glcm.patch.opatchautodb-actions_13.9.4.2.jar
/u01/app/oracle/product/19c/OPatch/auto/database/modules/helper
/u01/app/oracle/product/19c/OPatch/auto/database/modules/oplan_db.jar
/u01/app/oracle/product/19c/OPatch/auto/database/modules/oracle.glcm.opatchauto.db.helper.classpath.jar
/u01/app/oracle/product/19c/OPatch/auto/database/modules/oracle.glcm.opatchauto.db.systemmodel.classpath.jar
/u01/app/oracle/product/19c/OPatch/auto/database/modules/oracle.glcm.opatchauto.db.utils.classpath.jar
/u01/app/oracle/product/19c/OPatch/auto/database/modules/oracle.glcm.opatchauto.rhp.classpath.jar
/u01/app/oracle/product/19c/OPatch/auto/database/modules/oracle.oplan.db.classpath.jar
/u01/app/oracle/product/19c/OPatch/auto/database/modules/rhp
/u01/app/oracle/product/19c/OPatch/auto/database/modules/systemmodels
/u01/app/oracle/product/19c/OPatch/auto/database/modules/utils
/u01/app/oracle/product/19c/OPatch/auto/database/modules/helper/com.oracle.glcm.patch.db-comp-helper_13.9.4.2.jar
/u01/app/oracle/product/19c/OPatch/auto/database/modules/rhp/com.oracle.glcm.patch.opatchauto-rhp_13.9.4.2.jar
/u01/app/oracle/product/19c/OPatch/auto/database/modules/systemmodels/com.oracle.glcm.patch.db-comp-automation_13.9.4.2.jar
/u01/app/oracle/product/19c/OPatch/auto/database/modules/systemmodels/com.oracle.glcm.patch.db-comp-model_13.9.4.2.jar
/u01/app/oracle/product/19c/OPatch/auto/database/modules/systemmodels/com.oracle.glcm.patch.db-comp-patch-sdk_13.9.4.2.jar
/u01/app/oracle/product/19c/OPatch/auto/database/modules/systemmodels/com.oracle.glcm.patch.db-comp-productdriver_13.9.4.2.jar
/u01/app/oracle/product/19c/OPatch/auto/database/modules/utils/com.oracle.glcm.patch.db-systeminfogenerator_13.9.4.2.jar
/u01/app/oracle/product/19c/apex/images/apex/builder/database_app_128.png
/u01/app/oracle/product/19c/apex/images/apex_ui/img/favicons/app-artwork-catalog-16x16.png
/u01/app/oracle/product/19c/apex/images/apex_ui/img/favicons/app-artwork-catalog-32x32.png
/u01/app/oracle/product/19c/apex/images/apex_ui/img/favicons/app-artwork-catalog.ico
/u01/app/oracle/product/19c/apex/images/apex_ui/img/favicons/app-artwork-catalog.png
/u01/app/oracle/product/19c/apex/images/apex_ui/img/favicons/app-database-tools-16x16.png
/u01/app/oracle/product/19c/apex/images/apex_ui/img/favicons/app-database-tools-32x32.png
/u01/app/oracle/product/19c/apex/images/apex_ui/img/favicons/app-database-tools.ico
/u01/app/oracle/product/19c/apex/images/apex_ui/img/favicons/app-database-tools.png
/u01/app/oracle/product/19c/apex/images/apex_ui/img/favicons/app-sample-database-application-16x16.png
/u01/app/oracle/product/19c/apex/images/apex_ui/img/favicons/app-sample-database-application-32x32.png
/u01/app/oracle/product/19c/apex/images/apex_ui/img/favicons/app-sample-database-application.ico
/u01/app/oracle/product/19c/apex/images/apex_ui/img/favicons/app-sample-database-application.png
/u01/app/oracle/product/19c/apex/images/apex_ui/img/favicons/app-systems-catalog-16x16.png
/u01/app/oracle/product/19c/apex/images/apex_ui/img/favicons/app-systems-catalog-32x32.png
/u01/app/oracle/product/19c/apex/images/apex_ui/img/favicons/app-systems-catalog.ico
/u01/app/oracle/product/19c/apex/images/apex_ui/img/favicons/app-systems-catalog.png
/u01/app/oracle/product/19c/apex/images/apex_ui/img/icons/pkg-apps/app-artwork-catalog.png
/u01/app/oracle/product/19c/apex/images/apex_ui/img/icons/pkg-apps/app-sample-database-application.png
/u01/app/oracle/product/19c/apex/images/apex_ui/img/icons/pkg-apps/app-systems-catalog.png
/u01/app/oracle/product/19c/apex/images/apex_ui/img/icons_src/pkg-apps/app-artwork-catalog.svg
/u01/app/oracle/product/19c/apex/images/apex_ui/img/icons_src/pkg-apps/app-database-tools.svg
/u01/app/oracle/product/19c/apex/images/apex_ui/img/icons_src/pkg-apps/app-sample-database-application.svg
/u01/app/oracle/product/19c/apex/images/apex_ui/img/icons_src/pkg-apps/app-systems-catalog.svg
/u01/app/oracle/product/19c/apex/images/apex_ui/img/legacy/database_services_sprite.png
/u01/app/oracle/product/19c/apex/images/eba/img/app_screenshots/artwork_catalog.png
/u01/app/oracle/product/19c/apex/images/eba/img/app_screenshots/systems_catalog.png
/u01/app/oracle/product/19c/apex/images/htmldb/builder/database.gif
/u01/app/oracle/product/19c/apex/images/htmldb/builder/database_services_sprite.png
/u01/app/oracle/product/19c/apex/images/menu/database_bx_128x128.png
/u01/app/oracle/product/19c/apex/images/menu/ws_from_database.png
/u01/app/oracle/product/19c/apex/images/themes/oracle/pdbss/images/app_specific/600_database_12c_hero_bg.jpg
/u01/app/oracle/product/19c/apex/images/ws/ws_from_database.png
/u01/app/oracle/product/19c/network/tools/help/mgr/help/n8ahelpdatabase_identification_by_servi.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help/n8ahelpdatabase_link.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help/n8ahelpdatabase_services.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help/n8ahelpglobal_database_name.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help/n8ahelporacle_rdb_database.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help/n8ahelpregion_database.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help/n8ahelpstatically_configure_database_se.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help/home/mperugu/mgr_help/mgr_help/n8ahelpdatabase_identification_by_servi.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help/home/mperugu/mgr_help/mgr_help/n8ahelpdatabase_link.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help/home/mperugu/mgr_help/mgr_help/n8ahelpdatabase_services.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help/home/mperugu/mgr_help/mgr_help/n8ahelpglobal_database_name.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help/home/mperugu/mgr_help/mgr_help/n8ahelporacle_rdb_database.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help/home/mperugu/mgr_help/mgr_help/n8ahelpregion_database.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help/home/mperugu/mgr_help/mgr_help/n8ahelpstatically_configure_database_se.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_de/n8ahelpdatabase_identification_by_servi.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_de/n8ahelpdatabase_link.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_de/n8ahelpdatabase_services.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_de/n8ahelpglobal_database_name.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_de/n8ahelporacle_rdb_database.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_de/n8ahelpregion_database.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_de/n8ahelpstatically_configure_database_se.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_de/home/mperugu/mgr_help/mgr_help/n8ahelpdatabase_identification_by_servi.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_de/home/mperugu/mgr_help/mgr_help/n8ahelpdatabase_link.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_de/home/mperugu/mgr_help/mgr_help/n8ahelpdatabase_services.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_de/home/mperugu/mgr_help/mgr_help/n8ahelpglobal_database_name.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_de/home/mperugu/mgr_help/mgr_help/n8ahelporacle_rdb_database.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_de/home/mperugu/mgr_help/mgr_help/n8ahelpregion_database.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_de/home/mperugu/mgr_help/mgr_help/n8ahelpstatically_configure_database_se.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_es/n8ahelpdatabase_identification_by_servi.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_es/n8ahelpdatabase_link.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_es/n8ahelpdatabase_services.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_es/n8ahelpglobal_database_name.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_es/n8ahelporacle_rdb_database.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_es/n8ahelpregion_database.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_es/n8ahelpstatically_configure_database_se.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_es/home/mperugu/mgr_help/mgr_help/n8ahelpdatabase_identification_by_servi.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_es/home/mperugu/mgr_help/mgr_help/n8ahelpdatabase_link.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_es/home/mperugu/mgr_help/mgr_help/n8ahelpdatabase_services.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_es/home/mperugu/mgr_help/mgr_help/n8ahelpglobal_database_name.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_es/home/mperugu/mgr_help/mgr_help/n8ahelporacle_rdb_database.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_es/home/mperugu/mgr_help/mgr_help/n8ahelpregion_database.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_es/home/mperugu/mgr_help/mgr_help/n8ahelpstatically_configure_database_se.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_fr/n8ahelpdatabase_identification_by_servi.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_fr/n8ahelpdatabase_link.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_fr/n8ahelpdatabase_services.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_fr/n8ahelpglobal_database_name.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_fr/n8ahelporacle_rdb_database.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_fr/n8ahelpregion_database.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_fr/n8ahelpstatically_configure_database_se.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_fr/home/mperugu/mgr_help/mgr_help/n8ahelpdatabase_identification_by_servi.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_fr/home/mperugu/mgr_help/mgr_help/n8ahelpdatabase_link.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_fr/home/mperugu/mgr_help/mgr_help/n8ahelpdatabase_services.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_fr/home/mperugu/mgr_help/mgr_help/n8ahelpglobal_database_name.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_fr/home/mperugu/mgr_help/mgr_help/n8ahelporacle_rdb_database.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_fr/home/mperugu/mgr_help/mgr_help/n8ahelpregion_database.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_fr/home/mperugu/mgr_help/mgr_help/n8ahelpstatically_configure_database_se.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_it/n8ahelpdatabase_identification_by_servi.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_it/n8ahelpdatabase_link.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_it/n8ahelpdatabase_services.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_it/n8ahelpglobal_database_name.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_it/n8ahelporacle_rdb_database.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_it/n8ahelpregion_database.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_it/n8ahelpstatically_configure_database_se.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_it/home/mperugu/mgr_help/mgr_help/n8ahelpdatabase_identification_by_servi.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_it/home/mperugu/mgr_help/mgr_help/n8ahelpdatabase_link.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_it/home/mperugu/mgr_help/mgr_help/n8ahelpdatabase_services.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_it/home/mperugu/mgr_help/mgr_help/n8ahelpglobal_database_name.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_it/home/mperugu/mgr_help/mgr_help/n8ahelporacle_rdb_database.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_it/home/mperugu/mgr_help/mgr_help/n8ahelpregion_database.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_it/home/mperugu/mgr_help/mgr_help/n8ahelpstatically_configure_database_se.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_ja/n8ahelpdatabase_identification_by_servi.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_ja/n8ahelpdatabase_link.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_ja/n8ahelpdatabase_services.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_ja/n8ahelpglobal_database_name.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_ja/n8ahelporacle_rdb_database.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_ja/n8ahelpregion_database.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_ja/n8ahelpstatically_configure_database_se.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_ja/home/mperugu/mgr_help/mgr_help/n8ahelpdatabase_identification_by_servi.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_ja/home/mperugu/mgr_help/mgr_help/n8ahelpdatabase_link.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_ja/home/mperugu/mgr_help/mgr_help/n8ahelpdatabase_services.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_ja/home/mperugu/mgr_help/mgr_help/n8ahelpglobal_database_name.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_ja/home/mperugu/mgr_help/mgr_help/n8ahelporacle_rdb_database.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_ja/home/mperugu/mgr_help/mgr_help/n8ahelpregion_database.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_ja/home/mperugu/mgr_help/mgr_help/n8ahelpstatically_configure_database_se.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_ko/n8ahelpdatabase_identification_by_servi.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_ko/n8ahelpdatabase_link.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_ko/n8ahelpdatabase_services.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_ko/n8ahelpglobal_database_name.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_ko/n8ahelporacle_rdb_database.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_ko/n8ahelpregion_database.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_ko/n8ahelpstatically_configure_database_se.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_ko/home/mperugu/mgr_help/mgr_help/n8ahelpdatabase_identification_by_servi.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_ko/home/mperugu/mgr_help/mgr_help/n8ahelpdatabase_link.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_ko/home/mperugu/mgr_help/mgr_help/n8ahelpdatabase_services.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_ko/home/mperugu/mgr_help/mgr_help/n8ahelpglobal_database_name.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_ko/home/mperugu/mgr_help/mgr_help/n8ahelporacle_rdb_database.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_ko/home/mperugu/mgr_help/mgr_help/n8ahelpregion_database.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_ko/home/mperugu/mgr_help/mgr_help/n8ahelpstatically_configure_database_se.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_pt_BR/n8ahelpdatabase_identification_by_servi.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_pt_BR/n8ahelpdatabase_link.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_pt_BR/n8ahelpdatabase_services.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_pt_BR/n8ahelpglobal_database_name.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_pt_BR/n8ahelporacle_rdb_database.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_pt_BR/n8ahelpregion_database.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_pt_BR/n8ahelpstatically_configure_database_se.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_pt_BR/home/mperugu/mgr_help/mgr_help/n8ahelpdatabase_identification_by_servi.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_pt_BR/home/mperugu/mgr_help/mgr_help/n8ahelpdatabase_link.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_pt_BR/home/mperugu/mgr_help/mgr_help/n8ahelpdatabase_services.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_pt_BR/home/mperugu/mgr_help/mgr_help/n8ahelpglobal_database_name.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_pt_BR/home/mperugu/mgr_help/mgr_help/n8ahelporacle_rdb_database.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_pt_BR/home/mperugu/mgr_help/mgr_help/n8ahelpregion_database.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_pt_BR/home/mperugu/mgr_help/mgr_help/n8ahelpstatically_configure_database_se.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_zh_CN/n8ahelpdatabase_identification_by_servi.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_zh_CN/n8ahelpdatabase_link.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_zh_CN/n8ahelpdatabase_services.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_zh_CN/n8ahelpglobal_database_name.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_zh_CN/n8ahelporacle_rdb_database.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_zh_CN/n8ahelpregion_database.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_zh_CN/n8ahelpstatically_configure_database_se.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_zh_CN/home/mperugu/mgr_help/mgr_help/n8ahelpdatabase_identification_by_servi.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_zh_CN/home/mperugu/mgr_help/mgr_help/n8ahelpdatabase_link.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_zh_CN/home/mperugu/mgr_help/mgr_help/n8ahelpdatabase_services.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_zh_CN/home/mperugu/mgr_help/mgr_help/n8ahelpglobal_database_name.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_zh_CN/home/mperugu/mgr_help/mgr_help/n8ahelporacle_rdb_database.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_zh_CN/home/mperugu/mgr_help/mgr_help/n8ahelpregion_database.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_zh_CN/home/mperugu/mgr_help/mgr_help/n8ahelpstatically_configure_database_se.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_zh_TW/n8ahelpdatabase_identification_by_servi.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_zh_TW/n8ahelpdatabase_link.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_zh_TW/n8ahelpdatabase_services.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_zh_TW/n8ahelpglobal_database_name.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_zh_TW/n8ahelporacle_rdb_database.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_zh_TW/n8ahelpregion_database.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_zh_TW/n8ahelpstatically_configure_database_se.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_zh_TW/home/mperugu/mgr_help/mgr_help/n8ahelpdatabase_identification_by_servi.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_zh_TW/home/mperugu/mgr_help/mgr_help/n8ahelpdatabase_link.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_zh_TW/home/mperugu/mgr_help/mgr_help/n8ahelpdatabase_services.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_zh_TW/home/mperugu/mgr_help/mgr_help/n8ahelpglobal_database_name.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_zh_TW/home/mperugu/mgr_help/mgr_help/n8ahelporacle_rdb_database.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_zh_TW/home/mperugu/mgr_help/mgr_help/n8ahelpregion_database.htm
/u01/app/oracle/product/19c/network/tools/help/mgr/help_zh_TW/home/mperugu/mgr_help/mgr_help/n8ahelpstatically_configure_database_se.htm
/u01/app/oracle/product/19c/rdbms/admin/catalog.sql
/u01/app/oracle/product/19c/rdbms/admin/catalogses.sql
/u01/app/oracle/product/19c/rdbms/xml/em/image/database_cdb.png
/u01/app/oracle/product/19c/rdbms/xml/em/image/database_ena.png
/u01/app/oracle/product/19c/suptools/tfa/release/tfa_home/ext/dbglevel/profiles/database_resource_failure.xml
/u01/app/oracle/product/19c/suptools/tfa/release/tfa_home/resources/sql/srdc_gg_database.sql
/u01/app/oracle/product/19c/suptools/tfa/release/tfa_home/resources/sql/srdc_rman_validate_database.rcv
/usr/bin/oracle-database-preinstall-19c-verify
/usr/bin/update-desktop-database
/usr/bin/update-mime-database
/usr/bin/xmlcatalog
/usr/lib/systemd/catalog
/usr/lib/systemd/catalog/systemd.catalog
/usr/lib/systemd/catalog/systemd.fr.catalog
/usr/lib/systemd/catalog/systemd.it.catalog
/usr/lib/systemd/catalog/systemd.pl.catalog
/usr/lib/systemd/catalog/systemd.pt_BR.catalog
/usr/lib/systemd/catalog/systemd.ru.catalog
/usr/lib/systemd/system/systemd-journal-catalog-update.service
/usr/lib/systemd/system/sysinit.target.wants/systemd-journal-catalog-update.service
/usr/share/glade/catalogs
/usr/share/glade/catalogs/glade-catalog.dtd
/usr/share/glade/catalogs/gtk+.xml
/usr/share/glade/catalogs/gtkunixprint.xml
/usr/share/gnome-bluetooth/pin-code-database.xml
/usr/share/icons/hicolor/16x16/mimetypes/application-x-catalog.png
/usr/share/icons/hicolor/22x22/mimetypes/application-x-catalog.png
/usr/share/icons/hicolor/24x24/mimetypes/application-x-catalog.png
/usr/share/icons/hicolor/48x48/mimetypes/application-x-catalog.png
/usr/share/icons/hicolor/scalable/mimetypes/application-x-catalog.svg
/usr/share/licenses/oracle-database-preinstall-19c-1.0
/usr/share/licenses/oracle-database-preinstall-19c-1.0/LICENSE
/usr/share/man/man1/update-desktop-database.1.gz
/usr/share/man/man1/update-mime-database.1.gz
/usr/share/man/man1/xmlcatalog.1.gz
/usr/share/mime/application/vnd.oasis.opendocument.database.xml
/usr/share/sgml/docbook/xmlcatalog
/usr/share/vim/vim74/syntax/catalog.vim
/usr/share/yelp/dtd/catalog
/var/lib/systemd/catalog
/var/lib/systemd/catalog/database
/var/log/oracle-database-preinstall-19c
/var/log/oracle-database-preinstall-19c/backup
/var/log/oracle-database-preinstall-19c/results
/var/log/oracle-database-preinstall-19c/backup/May-30-2021-18-10-51
